services:
  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alumnet
    ports:
      - 1000:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./Back/alumnet.sql:/docker-entrypoint-initdb.d/dades.sql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8010:8080"

  laravel:
    #S'ha de fer un dockerfile amb PHP i Composer i les utilitats de docker per php per aixecar un servidor Laravel
    build: ./Back/Laravel
    ports:
      - 8020:8000
    volumes:
    #Quina carpeta LOCAL s'ha de mapejar / veure DINS del contenidor?
      - ./Back/Laravel:/var/www/
    working_dir: /var/www/
    depends_on:
      - db
    #Quan es crea, es poden executar ordres
    command: bash -c "composer install && php artisan key:generate && php artisan migrate:fresh --seed && php artisan serve --host=0.0.0.0" 

  vue:
    build: 
      context: ./Front
    ports:
      - 8030:5173
    volumes:
      - ./Front:/app
    depends_on:
      - laravel
    environment:
      VUE_APP_API_URL: http://laravel:8000
    command: bash -c "npm install && npm run dev"

  # node:
  #   build: 
  #     context: ./Back/Node
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./Back/Node:/node-app
  #     # crear una carpeta local para el node.js
  #   depends_on:
  #     - db
  #   working_dir: /node-app
  #   # command: bash -c "npm install && node (nom del fitxer node)"